---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-otel-query-nodeport
  namespace: observability
  labels:
    app: jaeger-otel-query
spec:
  type: NodePort
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      nodePort: 30686
  selector:
    app.kubernetes.io/name: jaeger-otel-query
    app.kubernetes.io/component: query

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-otel-collector-nodeport
  namespace: observability
  labels:
    app: jaeger-otel-collector
spec:
  type: NodePort
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30317
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30318
  selector:
    app.kubernetes.io/name: jaeger-otel-collector
    app.kubernetes.io/component: collector
