services:
  # Service account authentication middleware for OTEL endpoints
  auth-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4317:4319" # Service account protected OTLP gRPC
      - "4318:4319" # Service account protected OTLP HTTP
    depends_on:
      - jaeger
    networks:
      - default

  jaeger:
    # jaeger is a combination of OTLP collector and UI
    image: jaegertracing/all-in-one:latest
    environment:
      # Store spans in Elasticsearch
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector HTTP
      # Note: OTLP ports 4317/4318 are now handled by auth-middleware
      - "6831:6831/udp" # Jaeger agent UDP
    expose:
      - "4317" # Internal OTLP gRPC (accessed via auth-middleware)
      - "4318" # Internal OTLP HTTP (accessed via auth-middleware)
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601" # Kibana UI
    depends_on:
      elasticsearch:
        condition: service_healthy
volumes:
  esdata:
